# Generated by Django 4.2.9 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plowingservice",
            name="name",
            field=models.CharField(default="Plowing Service", max_length=100),
        ),
    ]
