# Generated by Django 4.2.9 on 2024-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plowing", "0002_plowingservice_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plowingrequest",
            old_name="requester",
            new_name="requestor",
        ),
        migrations.AlterField(
            model_name="plowingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plowingservice",
            name="name",
            field=models.CharField(default="Plowing Service", max_length=255),
        ),
    ]
